name: Experiment Submission
description: Submit a new experiment to run on the benchmarking framework
title: '[Experiment] '
labels:
- experiment
body:
- type: markdown
  attributes:
    value: 'Please fill out the following information to submit an experiment. The experiment will be run automatically and this issue will be closed when complete.

      '
- type: markdown
  attributes:
    value: '**Note:** This experiment will run across ALL available tasks automatically.

      '
- type: dropdown
  id: model
  attributes:
    label: Model Endpoint
    description: Select a model endpoint (or choose "Default" to use the default model, or "Other" to specify a custom model)
    options:
    - Default (global.anthropic.claude-sonnet-4-5-20250929-v1:0)
    - anthropic.claude-3-haiku-20240307-v1:0
    - us.anthropic.claude-haiku-4-5-20251001-v1:0
    - us.anthropic.claude-sonnet-4-20250514-v1:0
    - us.anthropic.claude-3-5-sonnet-20240620-v1:0
    - global.anthropic.claude-sonnet-4-5-20250929-v1:0
    - us.amazon.nova-premier-v1:0
    - us.amazon.nova-micro-v1:0
    - us.deepseek.r1-v1:0
    - openai.gpt-oss-20b-1:0
    - openai.gpt-oss-120b-1:0
    - Other
  validations:
    required: false
- type: input
  id: custom_model
  attributes:
    label: Custom Model Endpoint
    description: If you selected "Other" above, enter your custom model endpoint ID here (e.g., us.deepseek.r1-v1:0)
    placeholder: 'us.deepseek.r1-v1:0'
  validations:
    required: false
- type: textarea
  id: system_instructions
  attributes:
    label: System Instructions
    description: Custom system instructions (leave empty to use default). You can reference a file path or paste the instructions directly.
    placeholder: 'Option 1: Reference a file

      file:path/to/instructions.txt


      Option 2: Paste instructions directly

      Your custom system instructions here...

      '
  validations:
    required: false
- type: input
  id: temperature
  attributes:
    label: Temperature
    description: Sampling temperature (0.0-1.0, leave empty for default 0.0)
    placeholder: '0.0'
  validations:
    required: false
- type: dropdown
  id: thinking
  attributes:
    label: Thinking Mode
    description: Enable thinking/reasoning mode for supported models (e.g., Claude Sonnet 4.5)
    options:
    - 'false'
    - 'true'
  validations:
    required: false
- type: checkboxes
  id: tools
  attributes:
    label: Tools
    description: Select individual tools to enable for this experiment. Leave all unchecked for no tools.
    options:
    - label: ols_mcp
      description: OLS (Ontology Lookup Service) MCP API - retrieve ontology mappings, search for terms, get cross-products
    - label: zooma
      description: Map free-text annotations to ontology terms using ZOOMA API
    - label: fuzzy_match
      description: Find fuzzy matches for a value against a list of candidates using string similarity
    - label: fuzzy_match_schema
      description: Find fuzzy matches for a value against enum values in a JSON schema file
    - label: regex_tester
      description: Test and validate regex patterns against sample strings
    - label: schema_validator
      description: Validate data against a JSON schema
    - label: data_pattern_analyzer
      description: Analyze data patterns to infer data types (string, integer, date, boolean, email, URL)
  validations:
    required: false
- type: textarea
  id: description
  attributes:
    label: Experiment Description
    description: Optional description of what this experiment is testing
    placeholder: This experiment tests...
  validations:
    required: false
