name: Experiment Submission
description: Submit a new experiment to run on the benchmarking framework
title: '[Experiment] '
labels:
- experiment
body:
- type: markdown
  attributes:
    value: 'Please fill out the following information to submit an experiment. The experiment will be run automatically and this issue will be closed when complete.

      '
- type: markdown
  attributes:
    value: '**Note:** This experiment will run across ALL available tasks automatically.

      '
- type: dropdown
  id: model
  attributes:
    label: Model Endpoint
    description: Select a model endpoint (or choose "Default" to use the default model, or "Other" to specify a custom model)
    options:
    - Default (global.anthropic.claude-sonnet-4-5-20250929-v1:0)
    - '--- AWS Bedrock Models ---'
    - anthropic.claude-3-haiku-20240307-v1:0
    - us.anthropic.claude-haiku-4-5-20251001-v1:0
    - us.anthropic.claude-sonnet-4-20250514-v1:0
    - us.anthropic.claude-3-5-sonnet-20240620-v1:0
    - global.anthropic.claude-sonnet-4-5-20250929-v1:0
    - us.amazon.nova-premier-v1:0
    - us.amazon.nova-micro-v1:0
    - us.deepseek.r1-v1:0
    - openai.gpt-oss-20b-1:0
    - openai.gpt-oss-120b-1:0
    - '--- OpenRouter Models (requires OPENROUTER_API_KEY) ---'
    - '--- OpenAI ---'
    - openai/gpt-4-turbo
    - openai/gpt-4o
    - openai/gpt-4o-mini
    - openai/gpt-4o-2024-11-20
    - openai/gpt-4
    - openai/gpt-3.5-turbo
    - openai/o1
    - openai/o1-pro
    - openai/o3
    - openai/o3-mini
    - openai/o3-pro
    - openai/gpt-5
    - openai/gpt-5-mini
    - openai/gpt-5-pro
    - openai/gpt-5.1
    - openai/gpt-5.1-chat
    - openai/gpt-5.1-codex
    - openai/gpt-5.1-codex-mini
    - '--- Google ---'
    - google/gemini-3-pro-preview
    - google/gemini-2.5-pro
    - google/gemini-2.5-flash
    - google/gemini-2.0-flash-001
    - google/gemini-pro-1.5
    - google/gemini-flash-1.5
    - google/gemma-3-27b-it
    - google/gemma-3-12b-it
    - '--- Mistral AI ---'
    - mistralai/mistral-large
    - mistralai/mistral-large-2411
    - mistralai/mistral-medium-3.1
    - mistralai/mixtral-8x22b-instruct
    - mistralai/mixtral-8x7b-instruct
    - mistralai/codestral-2508
    - mistralai/mistral-small-3.2-24b-instruct
    - '--- DeepSeek ---'
    - deepseek/deepseek-chat-v3.1
    - deepseek/deepseek-chat
    - deepseek/deepseek-v3.1-terminus
    - deepseek/deepseek-prover-v2
    - '--- Qwen ---'
    - qwen/qwen3-max
    - qwen/qwen3-235b-a22b
    - qwen/qwen-plus
    - qwen/qwen-2.5-72b-instruct
    - qwen/qwen3-coder-plus
    - '--- Cohere ---'
    - cohere/command-r-plus-08-2024
    - cohere/command-r-08-2024
    - cohere/command-a
    - '--- xAI ---'
    - x-ai/grok-4
    - x-ai/grok-3
    - x-ai/grok-3-mini
    - '--- OpenRouter ---'
    - openrouter/sherlock-think-alpha
    - openrouter/sherlock-dash-alpha
    - openrouter/auto
    - '--- Perplexity ---'
    - perplexity/sonar-pro
    - perplexity/sonar-reasoning-pro
    - perplexity/sonar
    - '--- Other Providers ---'
    - microsoft/phi-4
    - microsoft/wizardlm-2-8x22b
    - ai21/jamba-large-1.7
    - inflection/inflection-3-productivity
    - Other
  validations:
    required: false
- type: input
  id: custom_model
  attributes:
    label: Custom Model Endpoint
    description: |
      If you selected "Other" above, enter your custom model endpoint ID here.
      - For AWS Bedrock: e.g., us.deepseek.r1-v1:0
      - For OpenRouter: e.g., openai/gpt-4, anthropic/claude-3-opus, google/gemini-pro
    placeholder: 'openai/gpt-4 or us.deepseek.r1-v1:0'
  validations:
    required: false
- type: textarea
  id: system_instructions
  attributes:
    label: System Instructions
    description: Custom system instructions (leave empty to use default). You can reference a file path or paste the instructions directly.
    placeholder: 'Option 1: Reference a file

      file:path/to/instructions.txt


      Option 2: Paste instructions directly

      Your custom system instructions here...

      '
  validations:
    required: false
- type: input
  id: temperature
  attributes:
    label: Temperature
    description: Sampling temperature (0.0-1.0, leave empty for default 0.0)
    placeholder: '0.0'
  validations:
    required: false
- type: dropdown
  id: thinking
  attributes:
    label: Thinking Mode
    description: Enable thinking/reasoning mode for supported models (e.g., Claude Sonnet 4.5)
    options:
    - 'false'
    - 'true'
  validations:
    required: false
- type: markdown
  attributes:
    value: '**Available Tools:**

      - **ols_mcp**: OLS (Ontology Lookup Service) MCP API - retrieve ontology mappings, search for terms, get cross-products
      - **zooma**: Map free-text annotations to ontology terms using ZOOMA API
      - **fuzzy_match**: Find fuzzy matches for a value against a list of candidates using string similarity
      - **fuzzy_match_schema**: Find fuzzy matches for a value against enum values in a JSON schema file
      - **regex_tester**: Test and validate regex patterns against sample strings
      - **schema_validator**: Validate data against a JSON schema
      - **data_pattern_analyzer**: Analyze data patterns to infer data types (string, integer, date, boolean, email, URL)
      - **synapse_sql_docs**: Access Synapse SQL query documentation and examples

      '
- type: checkboxes
  id: tools
  attributes:
    label: Tools
    description: Select individual tools to enable for this experiment. Leave all unchecked for no tools.
    options:
    - label: ols_mcp
    - label: zooma
    - label: fuzzy_match
    - label: fuzzy_match_schema
    - label: regex_tester
    - label: schema_validator
    - label: data_pattern_analyzer
    - label: synapse_sql_docs
  validations:
    required: false
- type: textarea
  id: description
  attributes:
    label: Experiment Description
    description: Optional description of what this experiment is testing
    placeholder: This experiment tests...
  validations:
    required: false
